version: '3.9'

services:
  web:
    build: .
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/sapience_trio
    ports:
      - 8000:8000
    env_file:
      - sapience_trio/.env
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=sapience_trio_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=sapience_trio_db
volumes:
  postgres_data: